<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Address;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // $bairros = [
        //     'Piacaveira',
        //     'Arembepe',
        //     'Phoc III',
        //     'Vilaa d Abrantes',
        //     'Dois d Julho',
        //     'Santo Antônio',
        //     'Monte Gordo',
        //     'Areias',
        //     'Catu d Abrantes',
        //     'Ponto Certo',
        //     'Nova Vitoria',
        //     'Barra do Jacuipe',
        //     'Verde Horizonte',
        //     'Gleba B',
        //     'Camacari d Dentro',
        //     'Novo Horizonte',
        //     'Gleba E',
        //     'Barra d Pojuca',
        //     'Buri Satuba',
        //     'Vilaa da Paz',
        //     'Gravata',
        //     'Parque Florestal',
        //     'Buri d Abrantes',
        //     'Parafuso',
        //     'Parque das Mangabas',
        //     'Ficam II',
        //     'Phoc II',
        //     'Parque Verde',
        //     'Jaua',
        //     'Cajazeiras',
        //     'Machadinho'
        // ];
        
        $bairros = [
            'Terminal',
            'Av. Eixo Urbano Central',
            'Rua Costa Pinto',
            'Rua Duque de Caxias',
            'Rua da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Luiz Gonzaga (Av. Oeste)',
            'Rua do Toco',
            'Rua Acácia Vermelha',
            'Rua das Flores',
            'Rua Acácia Rosa',
            'Rua das Aroeiras,',
            'Av. Eixo Urbano Sudoeste',
            'Rua Catuama',
            'Rua Acajutiba',
            'Av. Aliomar Baleeiro',
            'Rua da Glória (Gleba C)',
            'Rua Governador Mangabeira',
            'Rua Ibicaraí',
            'Rua Abaré',
            'Rua Triângulo do Leste',
            'Av. Comercial',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Eixo Urbano Central',
            'Rua Costa Pinto',
            'Rua Duque de Caxias',
            'Rua da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Rua das Almas',
            'Rua Triângulo do Leste',
            'Rua Abaré',
            'Rua Ibicaraí',
            'Rua Governador Mangabeira',
            'Rua da Glória (Gleba C)',
            'Av. Aliomar Baleeiro',
            'Rua Acajutiba',
            'Rua Catuama',
            'Av. Eixo Urbano Sudoeste',
            'Rua das Aroeiras',
            'Rua Acácia Rosa',
            'Rua das Flores',
            'Rua do Toco',
            'Av. Luiz Gonzaga (Av. Oeste)',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães (antiga Comercial)',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. Jorge Amado',
            'R. Lateral de Dentro (Vila Cantuária)',
            'Boulevard Shopping (R. Lateral)',
            'Av. Palmeiras',
            'Residencial Terra Brasilis',
            'Lucaia',
            'Condomínio Duo',
            'Cond. Duo',
            'Av. Industrial Urbana',
            'Av. Jorge Amado',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Av. Camassarys',
            'Boulevard',
            'Atacadão',
            'Av. Palmeiras',
            'Av. Camassarys',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'Rua Francisco Drumond',
            'Rua de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Senai/IFBA',
            'Rua Marlim Azul',
            'Av. Alameda',
            'Condomínio Viena',
            'Rua Marlim Branco',
            'Av. Alameda',
            'Condomínio Villa Bella',
            'Rua Marlim Azul',
            'Av. Jorge Amado',
            'Limpec',
            'Av. Palmeiras',
            'Rua Eucalipto',
            'Rua da Jabuticabeira',
            'Av. Parque das Palmeiras',
            'Av. Jorge Amado',
            'Rua de Contorno do Centro Administrativo',
            'Rua Delegado Clayton Leão Chaves',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'Rua Francisco Drumond',
            'Rua de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Senai/IFBA',
            'Retorno',
            'Av. Jorge Amado',
            'Rua Principal do Poloplast',
            'Rua B4',
            'Rua I',
            'Rua B2 Poloplast',
            'Rua Principal do Poloplast',
            'Av. Jorge Amado',
            'Rua de Contorno do Centro Administrativo',
            'Rua Delegado Clayton Leão Chaves',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'Rua Francisco Drumond',
            'Rua de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Senai/IFBA',
            'Rua Marlim Azul',
            'Av. Alameda',
            'Condomínio Viena',
            'Rua Marlim Branco',
            'Av. Alameda',
            'Condomínio Villa Bella',
            'Rua Marlim Azul',
            'Av. Jorge Amado',
            'Limpec',
            'Av. Palmeiras',
            'Rua Eucalipto',
            'Rua da Jabuticabeira',
            'Av. Parque das Palmeiras',
            'Av. Jorge Amado',
            'Rua Principal do Poloplast',
            'Rua B4',
            'Rua I',
            'Rua B2 Poloplast',
            'Rua Principal do Poloplast',
            'Av. Jorge Amado',
            'Rua de Contorno do Centro Administrativo',
            'Rua Delegado Clayton Leão Chaves',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Travessa Nossa Senhora do Carmo',
            'Rua Dois de Julho',
            'Rua Piaçaveira',
            'Rua Maranhão',
            'Rua Comendador Avelar',
            'Av. Sul',
            'Av. Lauro de Freitas',
            'Rua do Areal II',
            'Rua “Sem Denominação”',
            'Rua Direta da Massaranduba',
            'Rua Cora Coralina I',
            'Rua do Meio',
            'Rua Pantanal',
            'Rua da Massaranduba',
            'Rua Direta da Massaranduba',
            'Rua São Lázaro',
            'Rua do Areal II',
            'Av. Lauro de Freitas',
            'Av. Sul',
            'Rua Comendador Avelar',
            'Rua Cantuária',
            'Rua Piaçaveira',
            'Rua Dois de Julho',
            'Rua Dois de Maio',
            'Rua de Contorno do Centro Administrativo',
            'Terminal',
            'Residencial Parque das Algarobas',
            'Rua das Conchinhas',
            'Santa Maria',
            'R. Otávio Mangabeira (Lama Preta)',
            'Rua Flor do Campo',
            'Rua A',
            'Rua Peres',
            'R. Otávio Mangabeira',
            'Av. Rio Camaçari',
            'Rua Júlio Leitão',
            'Av. Concêntrica',
            'Hosp. Santa Helena',
            'Av. 28 Setembro',
            'R. Duque de Caxias',
            'Av. Eixo Urbano Central',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. Eixo Urbano',
            'R. Costa Pinto',
            'Av. 28 Setembro',
            'Av. Concêntrica',
            'Hosp. Santa Helena',
            'R. Júlio Leitão',
            'Av. Rio Camaçari',
            'R. Moreira César',
            'R. Otávio Mangabeira (Lama Preta)',
            'R. Orquídeas',
            'R. Santa Maria Adelina',
            'Rua A',
            'Rua Flor do Campo',
            'Santa Maria',
            'R. Conchinhas',
            'Residencial Parque das Algarobas',
            'Residencial Parque das Algarobas',
            'R. Conchinhas',
            'Rua da Prainha',
            'R. Otávio Mangabeira (Lama Preta)',
            'Rua Flor do Campo',
            'Rua A',
            'Rua Santa Maria Adelina',
            'R. Orquídeas',
            'R. Otávio Mangabeira',
            'R. Nova da Palha (Primeiro de Agosto)',
            'R. Felicidade',
            'Rua Santa Bárbara',
            'R. Nova Aliança',
            'Av. Luiz Gonzaga',
            'Av. Rio Camaçari',
            'Praça João Tamos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. Eixo Urbano',
            'R. Costa Pinto',
            'R. Duque de Caxias',
            'R. Bandeira',
            'Praça João Tamos Coroa (dos 46)',
            'Av. Luiz Gonzaga',
            'R. Nova Aliança',
            'R. Santa Bárbara',
            'Av. Otávio Mangabeira',
            'R. Orquídeas',
            'R. Santa Maria Adelina',
            'Rua A',
            'Rua Flor do Campo',
            'R. Otávio Mangabeira (Lama Preta)',
            'R. Prainha',
            'R. Conchinhas',
            'Residencial Parque das Algarobas',
            'Rua José Anchieta',
            'Residenciais Alpha 4/5',
            'Residenciais Morada dos Pardais 1/2/3',
            'Residenciais Morada dos Sabiás',
            'Residenciais Morada dos Canários',
            'R. Deputado Luís Eduardo Magalhães',
            'Praça da Harmonia',
            'R. Cajueiro',
            'Estrada 25',
            'R. Domingos dos Santos',
            'Principal do Limoeiro',
            'HGC',
            'Av. Jorge Amado',
            'Av. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Eixo Urbano Central',
            'R. Costa Pinto',
            'R. Duque de Caxias',
            'Av. Eixo Urbano Central',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Principal do Limoeiro',
            'R. Domingos dos Santos',
            'Estrada 25',
            'R. Cajueiro',
            'Praça da Harmonia',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. José Anchieta',
            'Residencial Morada dos Canários',
            'Residencial Morada dos Sabiás',
            'Residenciais Alphas 1/2/3',
            'Residenciais Morada dos Pardais 1/2/3',
            'Residencias Alpha 4/5',
            'Rua José Anchieta',
            'Residenciais Alpha 4/5',
            'Residenciais Moradas dos Pardais 1/2/3',
            'Residencial Morada dos Sabiás',
            'Residencial Morada dos Canários',
            'Rua José Anchieta',
            'Rua Boca da Capivara (Micos)',
            'Av. Jorge Amado',
            'Rua de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Eixo Urbano Central',
            'R. Costa Pinto',
            'R. Duque de Caxias',
            'Av. Eixo Urbano Central',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'R. Boca da Capivara (Micos)',
            'R. José Anchieta',
            'Residencial Morada dos Canários',
            'Residencial Morada dos Sabiás',
            'Residencias Alpha 1/2/3',
            'Residenciais Morada dos Pardais 1/2/3',
            'Residenciais Alpha 4/5',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. Eixo Urbano Central',
            'R. Costa Pinto',
            'R. Duque de Caxias',
            'Av. Dr. Manoel Mercês (antiga Radial B)',
            'Praça da Lua',
            'Av. Vereador Pedro Ribeiro de Freitas',
            'Av. Concêntrica',
            'Av. 28 de Setembro',
            'R. Duque de Caxias',
            'Av. Eixo Urbano Central',
            'R. Alecrim',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. 2 de Maio',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Rua de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'BA-535',
            'Via de Ligação',
            'R. Eteno',
            'BA-512',
            'Via Axial',
            'Via Axial',
            'Posto Trevo',
            'R. João Ursulo',
            'R. Hidrogênio',
            'R. Eteno',
            'Via de Ligação',
            'BA-535',
            'Av. Jorge Amado',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Fim de Linha da Gleba E',
            'R. Acácia Rosa',
            'R. das Flores',
            'R. Page',
            'R. Guarani',
            'Av. Luiz Gonzaga',
            'R. Acupe',
            'R. Campo Formoso',
            'R. Alagoinhas',
            'Av. Luiz Gonzaga',
            'Av. Rio Camaçari',
            'Av. Concêntrica',
            'Av. 28 Setembro',
            'R. Duque de Caxias',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. 2 de Maio',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Eixo Urbano Central',
            'R. Costa Pinto',
            'Av. 28 de Setembro',
            'Av. Concêntrica',
            'Av. Rio Camaçari',
            'Av. Luiz Gonzaga',
            'R. Alagoinhas',
            'R. Campo Formoso',
            'R. Acupe',
            'Av. Luiz Gonzaga',
            'R. Guanambi',
            'R. Guarani',
            'R. Page',
            'R. das Flores',
            'R. Acácia Rosa',
            'Fim de Linha da Gleba E',
            'Terminal',
            'Av. Eixo Urbano Central',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'R. das Almas',
            'R. Triângulo do Leste',
            'R. Abaré',
            'R. Martins XVII',
            'Trav. Açaí',
            'Av. Eixo Urbano Sudoeste',
            'R. Acácia Vermelha',
            'R. Climério de Oliveira',
            'R. Raquel de Queiroz',
            'Tv. Cora Coralina',
            'R. Cora Coralina',
            'R. Climério de Oliveira',
            'R. Acácia Vermelha',
            'Av. Eixo Urbano Sudoeste',
            'Tv. Açaí',
            'Av. Sul',
            'R. Martins XVII',
            'R. Abaré',
            'R. Triângulo do Leste',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. 2 de Maio',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Fim de Linha na Estação de Trem',
            'R. Marechal Floriano Peixoto',
            'R. Rafael',
            'BA-535 (Via Parafuso)',
            'HGC',
            'Av. Jorge Amado',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal do Boulevard Shopping',
            'BA-535 (Via Parafuso)',
            'R. Rafael',
            'R. Marechal Floriano Peixoto',
            'Fim de Linha na Estação de Trem',
            'Fim de Linha na Estação de Trem',
            '“Orla Parafuso”',
            'R. da Caixa D’Água',
            'R. Capela',
            'R. Comunitária',
            'R. Angico (Retorno)',
            'R. Comunitária',
            'R. Marechal Floriano Peixoto',
            'R. Rafael',
            'BA-535 (Via Parafuso)',
            'HGC',
            'Av. Jorge Amado',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal do Boulevard Shopping',
            'BA-535 (Via Parafuso)',
            'R. Areia',
            'R. Marechal Floriano Peixoto',
            'R. Comunitária',
            'R. Angico (Retorno)',
            'R. Comunitária',
            'R. Capela',
            'R. da Caixa D´Água',
            '“Orla Parafuso”',
            'Fim de Linha na Estação de Trem',
            'UNEB',
            'Copec',
            'Santo Antônio',
            'Residencial Parque São Vicente (Rua A',
            'Rua H e Rua A)',
            'Copec',
            'Av. 28 Setembro',
            'R. Duque de Caxias',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Eixo Urbano Central',
            'R. Costa Pinto',
            'R. Duque de Caxias',
            'Av. 28 Setembro',
            'Copec',
            'Residencial Parque São Vicente (Rua A',
            'Rua H e Rua A)',
            'Santo Antônio',
            'Copec',
            'UNEB',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Av. Eixo Urbano Central',
            'R. Costa Pinto',
            'R. Adelina de Sá',
            'R. do Telégrafo',
            'R. Irará',
            'Av. Florestal',
            'R. Sucupira',
            'R. Laranjeiras',
            'Av. Florestal',
            'R. 4ª Ligação',
            'R. Segundo Sendes',
            'R. 2ª Ligação',
            'Av. Tupinambás (antiga Radial C)',
            'Tv. Afrânio Peixoto',
            'R. Petrópolis',
            'Praça da Lua',
            'Av. Dr. Manoel Mercês (antiga Radial B)',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'R. do Alecrim',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. 2 de Maio',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'R. Costa Azul',
            'R. Ipanema',
            'R. Amaralina',
            'R. Casinhas do Verdes Horizontes',
            'R. Ponta Verde',
            'R. Pernambuco',
            'R. Atalaia',
            'R. Horizontes',
            'Av. Valdelice dos Santos de Souza',
            'R. Dom Avelar',
            'R. Comandante Avelar',
            'R. Alto da Bela Vista',
            'R. Abrantes',
            'R. Nova Camaçari (principal do Inocoop)',
            'Av. Sul',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Av. Sul',
            'R. Nova Camaçari (principal do Inocoop)',
            'R. Abrantes',
            'R. Alto da Bela Vista',
            'R. Comandante Avelar',
            'R. Dom Avelar',
            'Av. Valdelice Santos de Souza',
            'R. Horizontes',
            'R. Petrolina',
            'R. Pernambuco',
            'R. Ponta Verde',
            'R. Casinhas do Verdes Horizontes',
            'R. Amaralina',
            'R. Ipanema',
            'R. Costa Azul',
            'Fim de Linha do Sítio Verde',
            'Rua C',
            'Rua K',
            'R. Amaralina',
            'R. Casinhas do Verdes Horizontes',
            'R. Pernambuco',
            'R. Atalaia',
            'R. Horizontes',
            'Av. Valdelice Santos de Souza',
            'R. Dom Avelar',
            'Av. Sul',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'Terminal',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'R. de Contorno do Centro Administrativo',
            'Av. Sul',
            'Av. Valdelice Santos de Souza',
            'R. Horizontes',
            'R. Petrolina',
            'R. Pernambuco',
            'R. Ponta Verde',
            'R. Casinhas Verdes Horizontes',
            'R. Amaralina',
            'Rua K',
            'Rua C',
            'Fim de Linha do Sítio Verde',
            'Terminal',
            'R. Padre Paulo Maria Tonucci',
            'R. Bahia',
            'R. Eixo D',
            'Caminho D6',
            'R. Campinas',
            'R. Bahia',
            'Tv. Av. Leste',
            'Av. Jorge Amado',
            'R. de Contorno do Centro Administrativo',
            'Terminal',
            'R. Direta de Arembepe',
            'BA-099',
            'Barra do Jacuípe',
            'Cetrel',
            'Residenciais Caminho do Mar I',
            'II',
            'III',
            'Residencial Caminho do Rio',
            'Est. Canto dos Pássaros',
            'R. Direta Canto dos Pássaros',
            'Fim de Linha',
            'Fim de Linha',
            'R. Direta Canto dos Pássaros',
            'Est. Canto dos Pássaros',
            'Residencial Caminho do Rio',
            'Residenciais Caminho do Mar III',
            'II',
            'I',
            'Cetrel',
            'BA-099',
            'R. Direta de Arembepe',
            'R. Direta de Arembepe',
            'BA-099',
            'Outlet Premium',
            'R. Bosque',
            'R. Colônia Boa União',
            'Reserva Parque',
            'R. Espírito Santo',
            'Retorno Portão',
            'BA-099',
            'Av. Tiradentes (Abrantes)',
            'Entrada de Jauá',
            'R. Direta de Arembepe',
            'R. Direta de Arembepe',
            'BA-099',
            'Cascalheira',
            'Parafuso',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Avenida Tupinambá (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal Boulevard Shopping',
            'Parafuso',
            'Via Cascalheira',
            'R. Pé de Areia',
            'BA-099',
            'R. Direta de Arembepe',
            'Fim de Linha',
            'R. Direta Canto dos Pássaros',
            'Est. Canto dos Pássaros',
            'Residencial Caminho do Rio',
            'Residenciais Caminho do Mar III',
            'II',
            'I',
            'Cetrel',
            'Av. Jorge Amado',
            'HGC',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambás (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Cetrel',
            'Residenciais Caminho do Mar I',
            'II',
            'III',
            'Residencial Caminho do Rio',
            'Est. Canto dos Pássaros',
            'R. Direta Canto dos Pássaros',
            'Fim de Linha',
            'Fim de Linha de Fonte da Caixa',
            'Praça da Matriz',
            'R. Vieira de Mello',
            'Av. Tiradentes',
            'Dunas',
            'R. Aquárius',
            'R. Direta de Jauá',
            'Cascalheira',
            'Parafuso',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambás (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal do Boulevard Shopping',
            'Via Parafuso (BA-535)',
            'Cascalheira',
            'R. Pé de Areia',
            'R. Direta de Jauá',
            'R. Aquárius',
            'Dunas',
            'Av. Tiradentes',
            'R. João Araújo',
            'Praça da Matriz',
            'Fim de Linha de Fonte da Caixa',
            'Fim de Linha de Fonte da Caixa',
            'Praça da Matriz',
            'R. Vieira de Mello',
            'Av. Tiradentes',
            'Dunas',
            'R. Aquárius',
            'R. Direta de Jauá',
            'R. Belgrado',
            'R. Gajirus',
            'R. Costa do Marfim',
            'R. Pé de Areia',
            'Cascalheira',
            'Via Parafuso (BA-535)',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambás (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal Boulevard Shopping',
            'Via Parafuso (BA-535)',
            'Cascalheira',
            'R. Pé de Areia',
            'R. Direta de Jauá',
            'R. Aquárius',
            'Dunas',
            'Av. Tiradentes',
            'R. João Araújo',
            'Praça da Matriz',
            'R. da Grama',
            'Solar da Costa',
            'R. da Grama',
            'Fim de Linha de Fonte da Caixa',
            'Fim de Linha de Fonte da Caixa',
            'R. Grama',
            'Solar da Costa',
            'R. Grama',
            'Praça da Matriz',
            'R. Vieira de Mello',
            'Av. Tiradentes',
            'Dunas',
            'R. Aquárius',
            'R. Direta de Jauá',
            'Cascalheira',
            'Via Parafuso (BA-535)',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambás (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal Boulevard Shopping',
            'Via Parafuso (BA-535)',
            'Cascalheira',
            'R. Pé de Areia',
            'R. Direta de Jauá',
            'R. Aquárius',
            'Dunas',
            'Av. Tiradentes',
            'R. João Araújo',
            'Praça da Matriz',
            'R. da Grama',
            'Solar da Costa',
            'R. da Grama',
            'Fim de Linha de Fonte da Caixa',
            'Estação Rodoviária',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal do Boulevard Shopping',
            'Via Parafuso (Ba-535)',
            'Cascalheira',
            'Outlet Premium',
            'BA-099',
            'R. Bosque',
            'R. Colônia Boa União',
            'Reserva Parque',
            'R. Espírito Santo',
            'Retorno Portão',
            'BA-099',
            'Av. Tiradentes (Abrantes)',
            'Cascalheira',
            'Parafuso',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'Estação Rodoviária',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal Boulevard Shopping',
            'Via Parafuso (BA-535)',
            'Cascalheira',
            'Cajazeiras',
            'R. Lagoa Branca',
            'Morada Premium',
            'R. Sucupira',
            'Outlet Premium',
            'Alphaville Litoral Norte',
            'Alphaville Litoral Norte',
            'R. Principal Portal Abrantes',
            'R. Lagoa Branca',
            'Cajazeiras',
            'Cascalheira',
            'Via Parafuso (BA-535)',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'Rodoviária',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'Marginal Boulevard Shopping',
            'Via Parafuso (BA-535)',
            'Cascalheira',
            'Cajazeiras',
            'R. Lagoa Branca',
            'Morada Premium',
            'R. Sucupira',
            'Outlet Premium',
            'BA-099',
            'R. Bosque',
            'R. Colônia Boa União',
            'Reserva Parque',
            'R. Espírito Santo',
            'Retorno Portão',
            'BA-099',
            'Av. Tiradentes (Abrantes)',
            'Cascalheira',
            'Via Parafuso (BA-535)',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Direta de Arembepe',
            'BA-099 direto',
            'R. Filogônio Gomes de Oliveira',
            'R. Elísio Mello',
            'Fim de Linha no Campo Futebol',
            'Fim de Linha no Campo Futebol',
            'R. Elísio Mello',
            'R. Filogônio Gomes de Oliveira',
            'BA-099',
            'R. Direta de Arembepe',
            'R. Direta de Arembepe',
            'BA-099',
            'Barra do Jacuípe',
            'BA-529 (Estrada Velha)',
            'Corujão',
            'R. Sr. do Bonfim',
            'Guarajuba',
            'Guarajuba',
            'R. Sr. do Bonfim',
            'Corujão',
            'BA-529 (Estrada Velha)',
            'BA-099',
            'R. Direta de Arembepe',
            'Fim de Linha no Campo Futebol',
            'R. Elísio Mello',
            'R. Filogônio Gomes de Oliveira',
            'BA-099',
            'Cetrel',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambá (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputados Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Cetrel',
            'BA-099',
            'R. Filogônio Gomes de Oliveira',
            'R. Elísio Mello',
            'Fim de Linha no Campo Futebol',
            'Fim de Linha no Campo Futebol',
            'R. Elísio Mello',
            'R. Filogônio Gomes de Oliveira',
            'BA-099',
            'Itacimirim (Até Condomínio Enseada)',
            'BA-099',
            'Cetrel',
            'HGC',
            'Av. Jorge Amado',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambá (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Cetrel',
            'BA-099',
            'Itacimirim (Até Cond. Enseada)',
            'retorno BA-099',
            'R. Filogônio Gomes de Oliveira',
            'R. Elisio Mello',
            'Fim de Linha no Campo Futebol',
            'Fim de Linha na Igreja São Bento',
            'R. Largo de São Bento',
            'Feira',
            'Retorno Corujão',
            'BA-529 (Estrada Velha)',
            'BA-099',
            'Cetrel',
            'Av. Jorge Amado',
            'HGC',
            'Centro Administrativo',
            'Estação Rodoviária',
            'R. Eixo Urbano Central',
            'R. Feira',
            'R. Parque Central',
            'Av. Tupinambá (antiga Radial C)',
            'Praça Abrantes',
            'R. Duque de Caxias',
            'R. da Bandeira',
            'Praça João Ramos Coroa (dos 46)',
            'Av. Deputado Luís Eduardo Magalhães',
            'R. Francisco Drumond',
            'Centro Administrativo',
            'Av. Jorge Amado',
            'HGC',
            'Cetrel',
            'BA-099',
            'Retorno Jacuípe',
            'BA-529',
            'Feira',
            'Retorno Corujão',
            'R. Largo de São Bento',
            'Fim de Linha na Igreja São Bento'
          ];

        \App\Models\Company::factory()->create([
            "nome" => "admin",
            "email" => "admin@admin.com",
            "password" => bcrypt("123"),
            "cnpj" => "12.345.678/9012-34",
        ]);

        // foreach (array_values(array_unique($bairros)) as $bairro) {
        //     Address::factory()->create([
        //     'logradouro' => 'defaut',
        //         'bairro' => $bairro,
        //         'cidade' => 'Camaçari'
        //     ]);
        // }

        // \App\Models\Address::factory(25)->create();
        \App\Models\User::factory()->create([
            "nome" => "Usuario",
            "email" => "user@user.com",
            "password" => bcrypt("123"),
            "address_id" => 1,
        ]);
        \App\Models\User::factory(10)->create();
        // \App\Models\Company::factory(25)->create();
        // $this->call(AdminSeeder::class);
        // $this->call(UserSeeder::class);
        \App\Models\Feedback::factory(50)->create();
        \App\Models\BusOutbound::factory(30)->create();
        \App\Models\BusInbound::factory(30)->create();
        \App\Models\Route::factory(200)->create();
        // \App\Models\Bus::factory(5)->create();
        \App\Models\Itinerary::factory(3)->create();
        \App\Models\RequestedLocation::factory(50)->create();
        \App\Models\Request::factory(50)->create();
        \App\Models\UserOrigin::factory(50)->create();
        \App\Models\ItineraryHasRoute::factory(200)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);
    }
}
