-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 05:37:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema-tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema-tcc
-- -----------------------------------------------------
DROP SCHEMA `sistema-tcc`;
CREATE SCHEMA IF NOT EXISTS `sistema-tcc` DEFAULT CHARACTER SET utf8 ;
USE `sistema-tcc` ;

-- -----------------------------------------------------
-- Table `sistema-tcc`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_endereco` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_endereco`),
  INDEX `fk_usuarios_enderecos1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_usuarios_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sistema-tcc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`idas_onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`idas_onibus` (
  `id_destino` INT NOT NULL AUTO_INCREMENT,
  `id_endereco` INT NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`id_destino`, `id_endereco`),
  INDEX `fk_destinos_enderecos1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_destinos_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sistema-tcc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`onibus` (
  `id_onibus` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  `numeracao` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_onibus`, `id_empresa`),
  INDEX `fk_onibus_empresas1_idx` (`id_empresa` ASC),
  CONSTRAINT `fk_onibus_empresas1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `sistema-tcc`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`feedbacks` (
  `idfeedback` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `feedback` TINYINT NOT NULL,
  PRIMARY KEY (`idfeedback`),
  INDEX `fk_feedback_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_feedback_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema-tcc`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`requisicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`requisicoes` (
  `id_requisicao` INT NOT NULL AUTO_INCREMENT COMMENT 'Cada requisição representa a necessidade de viagem do usuário',
  `id_usuario` INT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `id_feedback` INT NULL,
  PRIMARY KEY (`id_requisicao`, `id_usuario`),
  INDEX `fk_requisicoes_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_requisicoes_feedbacks1_idx` (`id_feedback` ASC),
  CONSTRAINT `fk_requisicoes_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema-tcc`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requisicoes_feedbacks1`
    FOREIGN KEY (`id_feedback`)
    REFERENCES `sistema-tcc`.`feedbacks` (`idfeedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`voltas_onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`voltas_onibus` (
  `id_origem_onibus` INT NOT NULL AUTO_INCREMENT,
  `id_endereco` INT NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`id_origem_onibus`, `id_endereco`),
  INDEX `fk_origens_onibus_enderecos1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_origens_onibus_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sistema-tcc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`rotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`rotas` (
  `id_rota` INT NOT NULL AUTO_INCREMENT,
  `id_destino` INT NOT NULL,
  `id_origem_onibus` INT NULL,
  PRIMARY KEY (`id_rota`, `id_destino`),
  INDEX `fk_rotas_destinos1_idx` (`id_destino` ASC),
  INDEX `fk_rotas_origens_onibus1_idx` (`id_origem_onibus` ASC),
  CONSTRAINT `fk_rotas_destinos1`
    FOREIGN KEY (`id_destino`)
    REFERENCES `sistema-tcc`.`idas_onibus` (`id_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotas_origens_onibus1`
    FOREIGN KEY (`id_origem_onibus`)
    REFERENCES `sistema-tcc`.`voltas_onibus` (`id_origem_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`itinerarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`itinerarios` (
  `id_itinerario` INT NOT NULL AUTO_INCREMENT,
  `codigo_itinerario` VARCHAR(10) NOT NULL,
  `id_onibus` INT NOT NULL,
  `id_rota` INT NOT NULL,
  PRIMARY KEY (`id_itinerario`, `id_onibus`, `id_rota`),
  INDEX `fk_onibus_has_horarios_onibus1_idx` (`id_onibus` ASC),
  UNIQUE INDEX `numero_itinerario_UNIQUE` (`codigo_itinerario` ASC),
  INDEX `fk_itinerarios_rotas1_idx` (`id_rota` ASC),
  CONSTRAINT `fk_onibus_has_horarios_onibus1`
    FOREIGN KEY (`id_onibus`)
    REFERENCES `sistema-tcc`.`onibus` (`id_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itinerarios_rotas1`
    FOREIGN KEY (`id_rota`)
    REFERENCES `sistema-tcc`.`rotas` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`locais_requisitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`locais_requisitados` (
  `idlocal` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_endereco` INT NULL COMMENT 'O usuário pode requisita um local não cadastrado. Ao faze-lo, devo cadastra este local ainda que não se saiba qual é o endereço. A verificação do endereço deverá ser moderado pelo administrador?',
  PRIMARY KEY (`idlocal`),
  INDEX `fk_local_enderecos1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_local_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sistema-tcc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-tcc`.`origens_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-tcc`.`origens_usuarios` (
  `local_idlocal` INT NOT NULL,
  `requisicoes_id_requisicao` INT NOT NULL,
  `requisicoes_id_usuario` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `id_endereco` INT NULL,
  PRIMARY KEY (`local_idlocal`, `requisicoes_id_requisicao`, `requisicoes_id_usuario`),
  INDEX `fk_local_has_requisicoes_requisicoes1_idx` (`requisicoes_id_requisicao` ASC, `requisicoes_id_usuario` ASC),
  INDEX `fk_local_has_requisicoes_local1_idx` (`local_idlocal` ASC),
  INDEX `fk_origens_usuarios_enderecos1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_local_has_requisicoes_local1`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `sistema-tcc`.`locais_requisitados` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_has_requisicoes_requisicoes1`
    FOREIGN KEY (`requisicoes_id_requisicao` , `requisicoes_id_usuario`)
    REFERENCES `sistema-tcc`.`requisicoes` (`id_requisicao` , `id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_origens_usuarios_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sistema-tcc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;